# Generated by Django 4.1.4 on 2022-12-10 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_experiencecateg_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exp_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='experience_name',
            new_name='exp_name',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experienceCateg',
        ),
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(default=' ', max_length=50),
        ),
        migrations.DeleteModel(
            name='ExperienceCateg',
        ),
        migrations.AddField(
            model_name='exp_cat',
            name='exp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.experience'),
        ),
    ]
