# Generated by Django 4.1.4 on 2022-12-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_exp_cat_rename_experience_name_experience_exp_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='number',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='experience',
            name='exp_name',
            field=models.CharField(max_length=40),
        ),
    ]
